### ISSUE TITLE
Bug in data pre-processing?

### ISSUE THREAD

**Issue by andrkrav** [gabrielloye/LSTM_Sentiment-Analysis#1]
Hello Garbriel! I read your article on floydhub.com. Can you please clarify why you use 0 index for words which are not in word2idx

```python
for i, sentence in enumerate(train_sentences):
    # Looking up the mapping dictionary and assigning the index to the respective words
    train_sentences[i] = [word2idx[word] if word in word2idx else 0 for word in sentence]
```
It seems for me that it should be 1, which is index for _UNK
```python
# Adding padding and unknown to our vocabulary so that they will be assigned an index
words = ['_PAD','_UNK'] + words
# Dictionaries to store the word to index mappings and vice versa
word2idx = {o:i for i,o in enumerate(words)}
```

**Comment by gabrielloye** [comment]
> Hello Garbriel! I read your article on floydhub.com. Can you please clarify why you use 0 index for words which are not in word2idx
> 
> ```python
> for i, sentence in enumerate(train_sentences):
>     # Looking up the mapping dictionary and assigning the index to the respective words
>     train_sentences[i] = [word2idx[word] if word in word2idx else 0 for word in sentence]
> ```
> 
> It seems for me that it should be 1, which is index for _UNK
> 
> ```python
> # Adding padding and unknown to our vocabulary so that they will be assigned an index
> words = ['_PAD','_UNK'] + words
> # Dictionaries to store the word to index mappings and vice versa
> word2idx = {o:i for i,o in enumerate(words)}
> ```

Hi there, sorry for the delayed response! Yes, it is indeed an error, good spot! Thank you!
