### ISSUE TITLE
bug: using _PAD instead of _UNK in word lookup

### ISSUE THREAD

**Issue by stas00** [gabrielloye/LSTM_Sentiment-Analysis#2]
I don't have another way to contact you, but could you please fix a bug in your article:
https://blog.floydhub.com/long-short-term-memory-from-zero-to-hero-with-pytorch/

```
for i, sentence in enumerate(train_sentences):
    # Looking up the mapping dictionary and assigning the index to the respective words
    train_sentences[i] = [word2idx[word] if word in word2idx else 0 for word in sentence]

for i, sentence in enumerate(test_sentences):
    # For test sentences, we have to tokenize the sentences as well
    test_sentences[i] = [word2idx[word.lower()] if word.lower() in word2idx else 0 for word in nltk.word_tokenize(sentence)]
```

`else 0` should be `else 1` in both loops or much better `word2idx['_UNK']`.

I see you fixed the first half of it in this repo, but test_sentences is still `else 0`.

Thank you.

An excellent article/nb otherwise!

**Comment by gabrielloye** [comment]
Hi @stas00,

Apologies for the mistake! Thanks for pointing this out, I've since modified the code in the repo. Will try to get it changed in the article itself. Thank you!
